Prettify changelog for upcoming release
RadeonOpenCompute/amdsmi pull request #25
Opened 2024-05-03 16:50 UTC by peterjunpark

This PR makes CHANGELOG.md's formatting more consistent with other ROCm components ahead of 6.1.1 release.
- Reordered some headings.
- Made headings more consistent with other component docs.
- Added some periods.

2024-05-03 17:14 UTC, randyh62 approved these changes
Optimizations is just another word for Changes...

2024-05-07 20:31 UTC, marifamd requested changes
It turns out our changelog is too verbose. We talked with Roopa and the docs team and will shorten the changelog in a future release. As for the format, we follow the MLSE changelog where we have:

Each release will be in its own section (## level).

Each note will be in a subsection (### level). Please follow subsection-ordering. Subsections are:
- Changes - Behavior or features that change in functionality
- Additions - Features added to the software package
- Optimizations - Place performance optimization items in this section.
- Deprecations - Features that still work in the software package but will no longer be supported in the future.
- Removals - Announcements for deprecated features are removed from the software and no longer supported.
- Fixes - An issue known to the public whose functionality is fixed.
- Known issues - items in this list will roll over in the changelog for each release until they are announced in the “Fixed” subsection. There is an intention to have a issue tracking system available for use in the future. GitHub Issues is the logical choice but approvals are needed.
- Security - Security related announcements that will be tracked as a known issue. These are highlighted separately due to the risks involved.

2024-05-08 15:56 UTC, peterjunpark commented
Hi @marifamd, I'm aligned with what you're saying and I'm aware of the agreed-upon template.

>It turns out our changelog is too verbose. We talked with Roopa and the docs team and will shorten the changelog in a future release. As for the format, we follow the MLSE changelog where we have:

The docs team didn't want to include all of your changelog in the consolidated changelog on the ROCm docs portal because it's too long. The solution for 6.1.1 is to add an abbreviated version of your changelog and link to this repo where users can find more details.

Normally, the docs team cleans up each ROCm component's changelog before including it in the ROCm consolidated version. Since we cannot do that for this project and we're linking to this repo, I'd like to make it look consistent with other ROCm projects.

This PR only aligns your changelog's formatting with most of the other ROCm components.

2024-05-09 05:20 UTC, Rmalavally commented on CHANGELOG.md
>  This change was to help users to identify what range they can change the power cap of the GPU to. We added this to simplify why a device supports (or does not support) power capping (also known as ov
Looks good, Peter. Minor tweak,

Recommended:

This change helps users identify the range to which they can change the power cap of the GPU. The change is added to simplify why a device supports (or does not support) power capping (also known as overdrive). See `amd-smi set -g all --power-cap <value in W>` or `amd-smi reset -g all --power-cap.`

2024-05-09 05:22 UTC, Rmalavally approved these changes
Looks good, Peter.

2024-05-09 18:15 UTC, dmitrii-galantsev commented
perfect, I will merge internally and it will get pushed to github automagically. Thanks!
(please do not do anything else in this PR)

2024-05-10 10:31 UTC, merged